[package]
name = "cm256"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = ["simd"]
simd = []
compare = ["dep:raptorq", "dep:wirehair-wrapper"]

[dependencies]
raptorq = { version = "2.0.0", optional = true }
wirehair-wrapper = { version = "0.1.3", optional = true }

[[example]]
name = "benchmark"
path = "examples/benchmark.rs"

[[example]]
name = "compare_raptorq"
path = "examples/compare_raptorq.rs"
required-features = ["compare"]
