[package]
name = "cm256"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = ["simd"]
simd = []

[dependencies]
gf256 = { path = "gf256", default-features = false }

[dev-dependencies]
raptorq = "2.0.0"
wirehair-wrapper = "0.1.3"

[[example]]
name = "benchmark"
path = "examples/benchmark.rs"

[[example]]
name = "compare_raptorq"
path = "examples/compare_raptorq.rs"
